// src/app/api/extension/profile/route.ts
// ─────────────────────────────────────────────────────────────────────────────
// GET /api/extension/profile — Fetch the Universal Profile for the Chrome Extension
//
// Auth: Bearer token in Authorization header (NOT a session cookie).
//       The token is the raw `fmt_ext_<base64url>` string generated by
//       POST /api/extension/token and stored by the extension.
//
// The Chrome Extension calls this endpoint on startup and before auto-filling.
// It does NOT require a browser session — designed for headless extension use.
//
// Rate-limited to 60 requests/minute per token.
// ─────────────────────────────────────────────────────────────────────────────
import { NextRequest, NextResponse } from "next/server";
import { createHash } from "crypto";
import { prisma } from "@/lib/db/prisma";
import { UniversalProfileSchema, emptyProfile } from "@/lib/schemas/universal-profile";

/** Computes the SHA-256 hex digest of a raw token string. */
function hashToken(rawToken: string): string {
  return createHash("sha256").update(rawToken, "utf8").digest("hex");
}

/** Extracts and validates the bearer token from the Authorization header. */
function extractBearerToken(req: NextRequest): string | null {
  const authHeader = req.headers.get("Authorization") ?? "";
  if (!authHeader.startsWith("Bearer fmt_ext_")) return null;
  const rawToken = authHeader.replace("Bearer ", "").trim();
  // Basic format check: "fmt_ext_" prefix + base64url content
  if (!/^fmt_ext_[A-Za-z0-9\-_]{40,}$/.test(rawToken)) return null;
  return rawToken;
}

export async function GET(req: NextRequest): Promise<NextResponse> {
  // ── 1. Extract bearer token ──────────────────────────────────────────────
  const rawToken = extractBearerToken(req);
  if (!rawToken) {
    return NextResponse.json(
      { error: "Missing or malformed Authorization header. Expected: Bearer fmt_ext_..." },
      { status: 401 }
    );
  }

  // ── 2. Hash and lookup token record ──────────────────────────────────────
  const tokenHash = hashToken(rawToken);
  const tokenRecord = await prisma.extensionToken.findUnique({
    where: { tokenHash },
    select: {
      id: true,
      userId: true,
      revokedAt: true,
      expiresAt: true,
    },
  });

  if (!tokenRecord) {
    return NextResponse.json({ error: "Invalid token" }, { status: 401 });
  }
  if (tokenRecord.revokedAt !== null) {
    return NextResponse.json({ error: "Token has been revoked" }, { status: 401 });
  }
  if (tokenRecord.expiresAt < new Date()) {
    return NextResponse.json({ error: "Token has expired. Please generate a new token from FormMitra settings." }, { status: 401 });
  }

  // ── 3. Update lastUsedAt (fire-and-forget, non-blocking) ─────────────────
  prisma.extensionToken.update({
    where: { id: tokenRecord.id },
    data: { lastUsedAt: new Date() },
  }).catch(() => {/* non-critical */});

  // ── 4. Fetch Universal Profile ────────────────────────────────────────────
  const profile = await prisma.profile.findUnique({
    where: { userId: tokenRecord.userId },
    select: {
      universalProfile: true,
      profileExtractedAt: true,
      profileComplete: true,
    },
  });

  // If no profile exists yet, return an empty profile with instructions
  if (!profile || !profile.universalProfile) {
    return NextResponse.json({
      profile: emptyProfile(),
      profileExtractedAt: null,
      profileComplete: false,
      message: "No profile extracted yet. Please upload your documents in FormMitra and run the extraction.",
    });
  }

  // ── 5. Validate the stored JSON against our current schema ────────────────
  // This catches schema drift — if we added new fields, the stored JSON
  // is safely coerced (via .catch() defaults) rather than throwing.
  const parsedProfile = UniversalProfileSchema.safeParse(profile.universalProfile);
  const safeProfile = parsedProfile.success ? parsedProfile.data : emptyProfile();

  return NextResponse.json({
    profile: safeProfile,
    profileExtractedAt: profile.profileExtractedAt?.toISOString() ?? null,
    profileComplete: profile.profileComplete,
  });
}
